<?php

namespace Statamic\SeoPro\Robots;

use Statamic\Facades\Site;
use Statamic\Facades\URL;

class RobotsRenderer
{
    public function render(RobotsPolicy|array $policy): string
    {
        $values = $policy instanceof RobotsPolicy
            ? $policy->all()
            : Robots::withDefaults($policy);

        if ($values['mode'] === 'custom') {
            return $this->normalize($values['custom_source'] ?? '');
        }

        $lines = [
            '# Generated by Statamic SEO Pro',
            '',
        ];

        $lines = [...$lines, ...$this->group(['*'], $values, true)];

        foreach ($values['ai'] as $category => $access) {
            if ($access === 'neutral' || ! isset(BotRegistry::categories()[$category])) {
                continue;
            }

            $lines[] = '';
            $lines = [
                ...$lines,
                ...$this->group(
                    BotRegistry::categories()[$category],
                    $access === 'disallow'
                        ? ['allow' => [], 'disallow' => ['/'], 'content_signals' => []]
                        : $values,
                    $access === 'allow'
                ),
            ];
        }

        if ($values['include_sitemap'] && config('statamic.seo-pro.sitemap.enabled')) {
            foreach ($this->sitemapUrls() as $url) {
                $lines[] = '';
                $lines[] = 'Sitemap: '.$url;
            }
        }

        return $this->normalize(implode("\n", $lines));
    }

    private function group(array $userAgents, array $values, bool $includeSignals): array
    {
        $lines = collect($userAgents)
            ->map(fn (string $agent) => "User-agent: {$agent}")
            ->all();

        if ($includeSignals && $signal = $this->contentSignal($values['content_signals'] ?? [])) {
            $lines[] = $signal;
        }

        foreach ($values['allow'] ?? [] as $path) {
            $lines[] = "Allow: {$path}";
        }

        foreach ($values['disallow'] ?? [] as $path) {
            $lines[] = "Disallow: {$path}";
        }

        return $lines;
    }

    private function contentSignal(array $signals): ?string
    {
        $values = collect([
            'search' => $signals['search'] ?? null,
            'ai-input' => $signals['ai_input'] ?? null,
            'ai-train' => $signals['ai_train'] ?? null,
            'use' => $signals['use'] ?? null,
        ])->filter(fn ($value) => filled($value));

        if ($values->isEmpty()) {
            return null;
        }

        return 'Content-Signal: '.$values
            ->map(fn ($value, $key) => "{$key}={$value}")
            ->implode(', ');
    }

    private function sitemapUrls(): array
    {
        return Site::all()
            ->map(fn ($site) => URL::tidy(Robots::authority($site).'/'.config('statamic.seo-pro.sitemap.url'), false))
            ->unique()
            ->values()
            ->all();
    }

    private function normalize(string $contents): string
    {
        $contents = str_replace(["\r\n", "\r"], "\n", $contents);

        return rtrim($contents)."\n";
    }
}
