<?php

namespace Tests;

use Illuminate\Filesystem\Filesystem;
use Illuminate\Filesystem\LockableFile;
use Illuminate\Support\Facades\Event;
use PHPUnit\Framework\Attributes\Test;
use Statamic\Events\AddonSettingsSaved;
use Statamic\Facades\Addon;
use Statamic\SeoPro\Events\RobotsTxtGenerated;
use Statamic\SeoPro\Robots\Robots;
use Statamic\SeoPro\Robots\RobotsPolicy;
use Statamic\SeoPro\Robots\RobotsRenderer;
use Statamic\SeoPro\Robots\RobotsTxtGenerator;

class RobotsTest extends TestCase
{
    protected function tearDown(): void
    {
        $this->files->delete(public_path('robots.txt'));

        parent::tearDown();
    }

    #[Test]
    public function it_generates_a_neutral_robots_txt_with_the_sitemap()
    {
        $result = app(RobotsTxtGenerator::class)->generate();

        $this->assertSame(public_path('robots.txt'), $result['path']);
        $this->assertFileExists($result['path']);
        $this->assertEqualsIgnoringLineEndings(<<<'TXT'
# Generated by Statamic SEO Pro

User-agent: *
Allow: /

Sitemap: http://cool-runnings.com/sitemap.xml
TXT."\n", $this->files->get($result['path']));

        $status = app(RobotsTxtGenerator::class)->status();
        $this->assertTrue($status['exists']);
        $this->assertTrue($status['managed']);
        $this->assertNotNull($status['timestamp']);
    }

    #[Test]
    public function it_has_no_dynamic_frontend_route()
    {
        $this->assertFalse(app('router')->has('statamic.seo-pro.robots.show'));
        $this->get('/robots.txt')->assertNotFound();
    }

    #[Test]
    public function it_generates_managed_ai_rules_and_content_signals()
    {
        $policy = new RobotsPolicy([
            'ai' => [
                'search' => 'allow',
                'agent' => 'neutral',
                'training' => 'disallow',
            ],
            'content_signals' => [
                'search' => 'yes',
                'ai_input' => 'yes',
                'ai_train' => 'no',
                'use' => 'reference',
            ],
            'disallow' => ['/private/'],
        ]);

        $content = app(RobotsTxtGenerator::class)->generate($policy)['contents'];

        $this->assertStringContainsStringIgnoringLineEndings(<<<'TXT'
User-agent: *
Content-Signal: search=yes, ai-input=yes, ai-train=no, use=reference
Allow: /
Disallow: /private/
TXT, $content);

        $this->assertStringContainsStringIgnoringLineEndings(<<<'TXT'
User-agent: GPTBot
User-agent: ClaudeBot
User-agent: Google-Extended
User-agent: Applebot-Extended
User-agent: CCBot
User-agent: Meta-ExternalAgent
User-agent: Bytespider
Disallow: /
TXT, $content);
    }

    #[Test]
    public function custom_mode_preserves_source_and_only_normalizes_line_endings()
    {
        $policy = new RobotsPolicy([
            'mode' => 'custom',
            'custom_source' => "# Mine\r\nUser-agent: ExampleBot\r\nDisallow: /secret/\r\n\r\n",
        ]);

        app(RobotsTxtGenerator::class)->generate($policy);

        $this->assertSame(
            "# Mine\nUser-agent: ExampleBot\nDisallow: /secret/\n",
            $this->files->get(public_path('robots.txt')),
        );
    }

    #[Test]
    public function managed_rules_can_remove_the_default_allow_path()
    {
        $policy = new RobotsPolicy([
            'allow' => [],
            'disallow' => ['/private/'],
        ]);

        $content = app(RobotsTxtGenerator::class)->generate($policy)['contents'];

        $this->assertStringNotContainsString('Allow: /', $content);
        $this->assertStringContainsString('Disallow: /private/', $content);
    }

    #[Test]
    public function it_generates_custom_canonical_sitemap_urls()
    {
        $policy = new RobotsPolicy([
            'sitemap_mode' => 'custom',
            'sitemap_urls' => [
                'https://example.com/sitemap.xml',
                'https://example.de/sitemap.xml',
                'https://example.com/sitemap.xml',
            ],
        ]);

        $content = app(RobotsTxtGenerator::class)->generate($policy)['contents'];

        $this->assertSame(1, substr_count($content, 'Sitemap: https://example.com/sitemap.xml'));
        $this->assertSame(1, substr_count($content, 'Sitemap: https://example.de/sitemap.xml'));
        $this->assertStringNotContainsString('cool-runnings.com/sitemap.xml', $content);
    }

    #[Test]
    public function it_recognizes_unmanaged_and_modified_files()
    {
        $generator = app(RobotsTxtGenerator::class);
        $this->files->put(public_path('robots.txt'), "User-agent: *\nDisallow: /legacy/\n");

        $this->assertFalse($generator->status()['managed']);

        $generator->generate();
        $this->assertTrue($generator->status()['managed']);

        $this->files->append(public_path('robots.txt'), "# manually changed\n");
        $this->assertFalse($generator->status()['managed']);
    }

    #[Test]
    public function it_persists_settings_after_writing_and_dispatches_an_event()
    {
        Event::fake([RobotsTxtGenerated::class]);
        $policy = new RobotsPolicy(['disallow' => ['/private/']]);

        $result = app(RobotsTxtGenerator::class)->generate($policy);

        $this->assertFileExists($result['path']);
        $this->assertSame(['/private/'], Addon::get('statamic/seo-pro')->settings()->get('robots.policy.disallow'));
        $this->assertSame(hash('sha256', $result['contents']), Addon::get('statamic/seo-pro')->settings()->get('robots.generated.checksum'));

        Event::assertDispatched(RobotsTxtGenerated::class, fn ($event) => $event->path === public_path('robots.txt'));
    }

    #[Test]
    public function generating_an_up_to_date_file_is_a_no_op()
    {
        Event::fake([AddonSettingsSaved::class, RobotsTxtGenerated::class]);
        $files = new class extends Filesystem
        {
            public int $replacements = 0;

            public function replace($path, $content, $mode = null)
            {
                $this->replacements++;

                parent::replace($path, $content, $mode);
            }
        };
        $generator = new RobotsTxtGenerator($files, app(RobotsRenderer::class));

        $first = $generator->generate();
        $second = $generator->generate();

        $this->assertTrue($first['changed']);
        $this->assertTrue($first['settings_changed']);
        $this->assertFalse($second['changed']);
        $this->assertFalse($second['settings_changed']);
        $this->assertSame($first['timestamp'], $second['timestamp']);
        $this->assertSame(1, $files->replacements);
        Event::assertDispatchedTimes(AddonSettingsSaved::class, 1);
        Event::assertDispatchedTimes(RobotsTxtGenerated::class, 1);
    }

    #[Test]
    public function it_saves_a_changed_policy_without_rewriting_identical_contents()
    {
        Event::fake([AddonSettingsSaved::class, RobotsTxtGenerated::class]);
        $files = new class extends Filesystem
        {
            public int $replacements = 0;

            public function replace($path, $content, $mode = null)
            {
                $this->replacements++;

                parent::replace($path, $content, $mode);
            }
        };
        $generator = new RobotsTxtGenerator($files, app(RobotsRenderer::class));

        $first = $generator->generate(new RobotsPolicy(['preset' => 'neutral']));
        $second = $generator->generate(new RobotsPolicy(['preset' => 'custom']));

        $this->assertFalse($second['changed']);
        $this->assertTrue($second['settings_changed']);
        $this->assertSame($first['timestamp'], $second['timestamp']);
        $this->assertSame(1, $files->replacements);
        $this->assertSame('custom', Addon::get('statamic/seo-pro')->settings()->get('robots.policy.preset'));
        Event::assertDispatchedTimes(AddonSettingsSaved::class, 2);
        Event::assertDispatchedTimes(RobotsTxtGenerated::class, 1);
    }

    #[Test]
    public function it_restores_the_file_and_settings_when_a_post_save_event_fails()
    {
        $generator = app(RobotsTxtGenerator::class);
        $generator->generate(new RobotsPolicy(['disallow' => ['/previous/']]));
        $previousContents = $this->files->get(public_path('robots.txt'));
        $previousSettings = Robots::settingsSnapshot();
        $generatedEvents = 0;

        Event::listen(RobotsTxtGenerated::class, function () use (&$generatedEvents) {
            $generatedEvents++;
        });
        Event::listen(AddonSettingsSaved::class, function () {
            throw new \RuntimeException('The settings listener failed.');
        });

        try {
            $generator->generate(new RobotsPolicy(['disallow' => ['/changed/']]));
            $this->fail('Generation should have failed.');
        } catch (\RuntimeException $exception) {
            $this->assertSame('The settings listener failed.', $exception->getMessage());
        }

        $this->assertSame($previousContents, $this->files->get(public_path('robots.txt')));
        $this->assertSame($previousSettings, Robots::settingsSnapshot());
        $this->assertTrue($generator->status()['managed']);
        $this->assertFalse($generator->status()['outdated']);
        $this->assertSame(0, $generatedEvents);
        $this->assertSame([], glob(public_path('.seo-pro-robots-*')));
    }

    #[Test]
    public function it_removes_new_file_and_settings_when_first_generation_fails_after_saving()
    {
        $generator = app(RobotsTxtGenerator::class);
        $previousSettings = Robots::settingsSnapshot();
        $generatedEvents = 0;

        Event::listen(RobotsTxtGenerated::class, function () use (&$generatedEvents) {
            $generatedEvents++;
        });
        Event::listen(AddonSettingsSaved::class, function () {
            throw new \RuntimeException('The settings listener failed.');
        });

        try {
            $generator->generate();
            $this->fail('Generation should have failed.');
        } catch (\RuntimeException $exception) {
            $this->assertSame('The settings listener failed.', $exception->getMessage());
        }

        $this->assertFileDoesNotExist(public_path('robots.txt'));
        $this->assertSame($previousSettings, Robots::settingsSnapshot());
        $this->assertSame(0, $generatedEvents);
    }

    #[Test]
    public function it_restores_settings_when_a_settings_only_generation_fails()
    {
        $generator = app(RobotsTxtGenerator::class);
        $generator->generate(new RobotsPolicy(['preset' => 'neutral']));
        $previousContents = $this->files->get(public_path('robots.txt'));
        $previousSettings = Robots::settingsSnapshot();

        Event::listen(AddonSettingsSaved::class, function () {
            throw new \RuntimeException('The settings listener failed.');
        });

        try {
            $generator->generate(new RobotsPolicy(['preset' => 'custom']));
            $this->fail('Generation should have failed.');
        } catch (\RuntimeException $exception) {
            $this->assertSame('The settings listener failed.', $exception->getMessage());
        }

        $this->assertSame($previousContents, $this->files->get(public_path('robots.txt')));
        $this->assertSame($previousSettings, Robots::settingsSnapshot());
        $this->assertTrue($generator->status()['managed']);
        $this->assertFalse($generator->status()['outdated']);
    }

    #[Test]
    public function it_rejects_concurrent_generation_attempts()
    {
        $lock = new LockableFile(storage_path('framework/cache/seo-pro/robots-txt.lock'), 'c+');
        $lock->getExclusiveLock();

        try {
            app(RobotsTxtGenerator::class)->generate();
            $this->fail('Concurrent generation should have failed.');
        } catch (\RuntimeException $exception) {
            $this->assertStringContainsString('generation lock', $exception->getMessage());
        } finally {
            $lock->close();
        }

        $this->assertFileDoesNotExist(public_path('robots.txt'));
        $this->assertFalse(Robots::settingsSnapshot()['exists']);
    }

    #[Test]
    public function it_reads_the_previous_site_scoped_settings_as_a_shared_policy()
    {
        $settings = Addon::get('statamic/seo-pro')->settings();
        $settings->set('robots', [
            'default' => [
                'mode' => 'custom',
                'preset' => 'open',
                'custom_source' => "User-agent: *\nDisallow: /legacy/",
            ],
        ])->save();

        $this->assertSame('custom', Robots::get()->all()['mode']);
        $this->assertSame('full', Robots::get()->all()['preset']);
        $this->assertStringContainsString('/legacy/', Robots::get()->all()['custom_source']);
    }
}
