<?php

namespace Tests;

use Illuminate\Support\Facades\Event;
use PHPUnit\Framework\Attributes\Test;
use Statamic\Facades\Addon;
use Statamic\SeoPro\Events\RobotsTxtGenerated;
use Statamic\SeoPro\Robots\Robots;
use Statamic\SeoPro\Robots\RobotsPolicy;
use Statamic\SeoPro\Robots\RobotsTxtGenerator;

class RobotsTest extends TestCase
{
    protected function tearDown(): void
    {
        $this->files->delete(public_path('robots.txt'));

        parent::tearDown();
    }

    #[Test]
    public function it_generates_a_neutral_robots_txt_with_the_sitemap()
    {
        $result = app(RobotsTxtGenerator::class)->generate();

        $this->assertSame(public_path('robots.txt'), $result['path']);
        $this->assertFileExists($result['path']);
        $this->assertSame(<<<'TXT'
# Generated by Statamic SEO Pro

User-agent: *
Allow: /

Sitemap: http://cool-runnings.com/sitemap.xml
TXT."\n", $this->files->get($result['path']));

        $status = app(RobotsTxtGenerator::class)->status();
        $this->assertTrue($status['exists']);
        $this->assertTrue($status['managed']);
        $this->assertNotNull($status['timestamp']);
    }

    #[Test]
    public function it_has_no_dynamic_frontend_route()
    {
        $this->assertFalse(app('router')->has('statamic.seo-pro.robots.show'));
        $this->get('/robots.txt')->assertNotFound();
    }

    #[Test]
    public function it_generates_managed_ai_rules_and_content_signals()
    {
        $policy = new RobotsPolicy([
            'ai' => [
                'search' => 'allow',
                'agent' => 'neutral',
                'training' => 'disallow',
            ],
            'content_signals' => [
                'search' => 'yes',
                'ai_input' => 'yes',
                'ai_train' => 'no',
                'use' => 'reference',
            ],
            'disallow' => ['/private/'],
        ]);

        $content = app(RobotsTxtGenerator::class)->generate($policy)['contents'];

        $this->assertStringContainsStringIgnoringLineEndings(<<<'TXT'
User-agent: *
Content-Signal: search=yes, ai-input=yes, ai-train=no, use=reference
Allow: /
Disallow: /private/
TXT, $content);

        $this->assertStringContainsStringIgnoringLineEndings(<<<'TXT'
User-agent: GPTBot
User-agent: ClaudeBot
User-agent: Google-Extended
User-agent: Applebot-Extended
User-agent: CCBot
User-agent: Meta-ExternalAgent
User-agent: Bytespider
Disallow: /
TXT, $content);
    }

    #[Test]
    public function custom_mode_preserves_source_and_only_normalizes_line_endings()
    {
        $policy = new RobotsPolicy([
            'mode' => 'custom',
            'custom_source' => "# Mine\r\nUser-agent: ExampleBot\r\nDisallow: /secret/\r\n\r\n",
        ]);

        app(RobotsTxtGenerator::class)->generate($policy);

        $this->assertSame(
            "# Mine\nUser-agent: ExampleBot\nDisallow: /secret/\n",
            $this->files->get(public_path('robots.txt')),
        );
    }

    #[Test]
    public function managed_rules_can_remove_the_default_allow_path()
    {
        $policy = new RobotsPolicy([
            'allow' => [],
            'disallow' => ['/private/'],
        ]);

        $content = app(RobotsTxtGenerator::class)->generate($policy)['contents'];

        $this->assertStringNotContainsString('Allow: /', $content);
        $this->assertStringContainsString('Disallow: /private/', $content);
    }

    #[Test]
    public function it_recognizes_unmanaged_and_modified_files()
    {
        $generator = app(RobotsTxtGenerator::class);
        $this->files->put(public_path('robots.txt'), "User-agent: *\nDisallow: /legacy/\n");

        $this->assertFalse($generator->status()['managed']);

        $generator->generate();
        $this->assertTrue($generator->status()['managed']);

        $this->files->append(public_path('robots.txt'), "# manually changed\n");
        $this->assertFalse($generator->status()['managed']);
    }

    #[Test]
    public function it_persists_settings_after_writing_and_dispatches_an_event()
    {
        Event::fake([RobotsTxtGenerated::class]);
        $policy = new RobotsPolicy(['disallow' => ['/private/']]);

        $result = app(RobotsTxtGenerator::class)->generate($policy);

        $this->assertFileExists($result['path']);
        $this->assertSame(['/private/'], Addon::get('statamic/seo-pro')->settings()->get('robots.policy.disallow'));
        $this->assertSame(hash('sha256', $result['contents']), Addon::get('statamic/seo-pro')->settings()->get('robots.generated.checksum'));

        Event::assertDispatched(RobotsTxtGenerated::class, fn ($event) => $event->path === public_path('robots.txt'));
    }

    #[Test]
    public function it_reads_the_previous_site_scoped_settings_as_a_shared_policy()
    {
        $settings = Addon::get('statamic/seo-pro')->settings();
        $settings->set('robots', [
            'default' => [
                'mode' => 'custom',
                'preset' => 'open',
                'custom_source' => "User-agent: *\nDisallow: /legacy/",
            ],
        ])->save();

        $this->assertSame('custom', Robots::get()->all()['mode']);
        $this->assertSame('full', Robots::get()->all()['preset']);
        $this->assertStringContainsString('/legacy/', Robots::get()->all()['custom_source']);
    }
}
