open_graph_image_width: 1200
open_graph_image_height: 1200
sitemap_enabled: true
sitemap_url: sitemap.xml
sitemap_cache_length: 60

defaults:
  site_name: 'Site Name'
  site_name_position: 'after'
  site_name_separator: '|'
  title: '@seo:title'
  description: '@seo:content'
  priority: 0.5
  change_frequency: monthly
humans:
  enabled: true
  content: |
    /* TEAM */

    Creator: {{ site_name }}
    URL: {{ site_url }}
    Description: {{ description }}

    /* THANKS */

    Statamic: https://statamic.com

    /* SITE */

    Standards: HTML5, CSS3
    Components: Statamic 2, Laravel, PHP, JavaScript
robots:
  enabled: true
  content: |
    User-agent: *
    Disallow: /