name: SEO Pro
version: '1.3.2'
description: Search Engine Optimization tools.
url: 'https://statamic.com/marketplace/addons/seo-pro'
developer: Statamic
developer_url: 'https://statamic.com'
commercial: true

fieldtype_fields:
  fields:
    type: seo_pro.fields
source_fieldtype_fields:
  field:
    type: seo_pro.source_field
